### ISSUE TITLE
Stream stopping in between

### ISSUE THREAD

**Issue by MjJuneja** [Roverr/rtsp-stream#19]
Stream work properly for some time and then stops suddenly. And keep reloading for previous 6-8 seconds recorded stream.

**Comment by Roverr** [comment]
Sorry I did not have time yet to check out this issue. Can you provide me more information about this? @MjJuneja 

When and how did you experience this bug?
What kind of environment did you use?
Are you sure that the given network is able to provide the required bandwidth?
Is there anyway you could reproduce this consistently?

Thanks!
