### ISSUE TITLE
timed out while waiting for file creation in manager start

### ISSUE THREAD

**Issue by Barmunksu** [Roverr/rtsp-stream#22]
clear centos 7 without iptables

> POST http://app/start {"uri": "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov"}

> root@docker-s-1vcpu-1gb-fra1-01:~# docker run -p 80:8080 roverr/rtsp-stream:1
> time="2019-08-16T12:23:11Z" level=info msg="RTSP-STREAM started on 8080"
> time="2019-08-16T12:23:29Z" level=info msg="wowzaec2demo-streamlock-net-vod-mp4-bigbuckbunny-115k-mov started processing"
> time="2019-08-16T12:23:49Z" level=error msg="./videos/wowzaec2demo-streamlock-net-vod-mp4-bigbuckbunny-115k-mov/index.m3u8 timed out while waiting for file creation in manager start"
> panic: send on closed channel
> 
> goroutine 15 [running]:
> github.com/Roverr/rtsp-stream/core.Manager.Start.func3.1()
>         /go/src/github.com/Roverr/rtsp-stream/core/manager.go:98 +0x106
> sync.(*Once).Do(0xc000018ef0, 0xc00002a788)
>         /usr/local/go/src/sync/once.go:44 +0xb3
> github.com/Roverr/rtsp-stream/core.Manager.Start.func3(0x4a817c800, 0xc000018ef0, 0xc000014410, 0x4d, 0xc00004c0e0)
>         /go/src/github.com/Roverr/rtsp-stream/core/manager.go:96 +0x95
> created by github.com/Roverr/rtsp-stream/core.Manager.Start
>         /go/src/github.com/Roverr/rtsp-stream/core/manager.go:94 +0x12d
> root@docker-s-1vcpu-1gb-fra1-01:~#

**Comment by willyjchen** [comment]
In version 1.4.3, there is a bug that shows "timeout" at 15s then "panic" at 20s when the source rtsp is unavailable. You may check the source again.

**Comment by Roverr** [comment]
Hi @willyjchen,
Thanks for opening this issue and sorry for leaving you alone with it for so long. I had a lot of stuff going on and was not able to pay attention to this until now.

Yes you are right on this, I was able to reproduce the panic. I've fixed this issue in `v1.5.0`. Now the manager should not panic in this cases. There was a bug around closing the channel that is used for communication between the controller layer and the processing.

Official docker images are also updated. Please feel free to reopen this issue if you are experiencing this again.
