### ISSUE TITLE
Network Error with UI

### ISSUE THREAD

**Issue by Streamversetv** [Roverr/rtsp-stream#36]
I got the UI running on my Synology DS916+ with Docker. 

When posting the link of my rtsp-ip camera I get an "Error: Network Error".

Here's the whole browser error log:

Error: Network Error
    at module.exports (createError.js:16)
    at XMLHttpRequest.p.onerror (xhr.js:81)
POST http://127.0.0.1:8080/start net::ERR_CONNECTION_REFUSED
- (anonymous) @ xhr.js:172
- module.exports @ xhr.js:11
- module.exports @ dispatchRequest.js:57
- Promise.then (async)
- s.request @ Axios.js:53
- s.<computed> @ Axios.js:78
- (anonymous) @ bind.js:9
- value @ api.js:19
- value @ App.jsx:37
- value @ Button.js:42
- a @ react-dom.production.min.js:14
- f @ react-dom.production.min.js:15
- d @ react-dom.production.min.js:15
- E @ react-dom.production.min.js:17
- P @ react-dom.production.min.js:18
- S @ react-dom.production.min.js:18
- D @ react-dom.production.min.js:21
- In @ react-dom.production.min.js:84
- Ki @ react-dom.production.min.js:231
- Le @ react-dom.production.min.js:39
- Fn @ react-dom.production.min.js:86
- Yi @ react-dom.production.min.js:231
- On @ react-dom.production.min.js:85

What might be the issue?

Thanks

**Comment by Roverr** [comment]
Hi @Streamversetv ,

Seems like you are not exposing the port of the backend. As the UI states in the description it has to be exposed on the running container.
`docker run -p 8080:8080 -p 80:80 roverr/rtsp-stream:2-management`

The reason for this is that currently it is burnt into the code as the URL of the backend.

**Comment by Roverr** [comment]
Let me know if your problem persists
