### ISSUE TITLE
streams registered in config yaml

### ISSUE THREAD

**Issue by darren-martz** [Roverr/rtsp-stream#37]
Is there a way to pre-start RTSP streams from the config file where the HTTP end points are consistent? That would really help out for restarting and updating the container, but not having to reset all the clients and reset all the feeds. Maybe there is a way already for that?

**Comment by darren-mayne** [comment]
I added a pull request #38 to address this.

**Comment by Roverr** [comment]
Closing this because [#38](https://github.com/Roverr/rtsp-stream/pull/38). Thanks for contribution! 🎉
