### ISSUE TITLE
How to keep ffmpeg always transing？

### ISSUE THREAD

**Issue by zaozhao** [Roverr/rtsp-stream#40]
My project always needs  transing hls , so i want to know how to do .I can't fand the key of this.

**Comment by zaozhao** [comment]
thanks a lot ~

**Comment by zaozhao** [comment]
thanks

**Comment by Roverr** [comment]
Hi @zaozhao ,

Absolutely fair point, documentation was missing the env variable you need to turn off the clean up functionality (so inactivity is not a problem anymore).

You have to set `RTSP_STREAM_CLEANUP_ENABLED` to `false`

I added the variable to the configuration document

Thanks for opening the issue!
