### ISSUE TITLE
VPN stream not loading

### ISSUE THREAD

**Issue by RamanChola** [Roverr/rtsp-stream#73]
I have a rstp stream which only runs when we are connected to the vpn. But when I convert that rtsp while I am connected to the vpn to hls stream, the stream only buffers and doesn't plays. 
p.s. - The rtsp stream works fine in VLC media player.

It would be appreciated if anyone could help me debug this issue!

**Comment by bhatiaharshit07** [comment]
It was a codec related issue xD
H.265 cant be played on browsers yet but VLC supports it.

**Comment by bhatiaharshit07** [comment]
> I have a rstp stream which only runs when we are connected to the vpn. But when I convert that rtsp while I am connected to the vpn to hls stream, the stream only buffers and doesn't plays. p.s. - The rtsp stream works fine in VLC media player.
> 
> It would be appreciated if anyone could help me debug this issue!
########################################################
It was a codec related issue xD
H.265 cant be played on browsers yet but VLC supports it.
